### ISSUE TITLE
Test UI Issues

### ISSUE THREAD

**Issue by Anuragtech02** [Iitpulse/client-test#12]
- [x] Check Test Timer
- [x] Legend UI Correction -> Width of Answered and Marked for review
- [x] Cursor pointer on options
- [ ] Collapse not working
- [x] Instead of JS alert, use the internal modal
- [x] Remove quotes from `Button` component

**Comment by Anuragtech02** [comment]
@DeepakKewadia 
Any update?

**Comment by DeepakKewadia** [comment]
almost done.
need some help.
